language: cpp

python:
  - "2.7"

before_install:
  - sudo apt-get install python-pexpect

install:
  - wget https://sourceforge.net/projects/astyle/files/astyle/astyle%202.05.1/astyle_2.05.1_linux.tar.gz/download -O astyle.tar.gz
  - tar -xzvf astyle.tar.gz
  - pushd astyle/build/gcc && make && sudo make install
  - popd

script:
  - ./bootstrap-configure --enable-minimum-set-of-tests
  - make pretty-check
  - make check
